### PR TITLE
Solution_to_Quiz_1

### PR DESCRIPTION
**Pull request by ansonws**

### CODE REVIEW

**Review by QuickStyles — APPROVED** [review]
## Scoresheet for Anson Lam
## Score: 93%/100%
#### LEGEND
|Icon |Value |
|--------|-----|
|&#10003;|correct|
|&#10007;|wrong|

# Build, Cluckr, a simple twitter clone with Express.

# Part 1: Application Skeleton
### Value: 10%
## Score: 10/10%

Build an Express app with the following:

|Feature |Mark |Notes |
|--------|-----|------|
|Logging middleware installed|&#10003;||
|Logging middleware setup|&#10003;||
|Nodemon installed as a developement dependency|&#10003;||
|Nodemon setup as an npm script|&#10003;||
|static assets middleware setup|&#10003;||

------
# Part 2: Sign In
### Value: 10%
## Score: 10/10%

|Feature |Mark |Notes |
|--------|-----|------|
|create get "/sign_in" route|&#10003;||
|get "/sign_in" renders a template that contains a form with username field|&#10003;||
|create post "/sign_in" route|&#10003;||
|post "/sign_in" creates a cookie|&#10003;||
|create post "/sign_out" route that destorys cookie|&#10003;||

------
# Part 3: Clucks
### Value: 10%
## Score: 10/10%

|Feature |Mark |Notes |
|--------|-----|------|
|knexfile setup correctly|&#10003;||
|knex migration created correctly|&#10003;||

------
# Part 4: Create Clucks
### Value: 20%
## Score: 20/20%

|Feature |Mark |Notes |
|--------|-----|------|
|in the entry point (app.js/index.js) get '/cluckr' should be handled by a seperate router imported from a different file|&#10003;||
|allow only user that is signed in to create clucks|&#10003;||
|submittions should add a record to the database|&#10003;||
|user should be able to give link to an image url|&#10003;||
|cluck record should get it's name from the cookie|&#10003;||
|successfully created clucks should redirect to index page|&#10003;||

------
# Part 5: The Clucks Index
### Value: 25%
## Score: 20/25%

|Feature |Mark |Notes |
|--------|-----|------|
|page should list all clucks|&#10007;|Only listing user's clucks...):|
|clucks should be ordered by creation date|&#10003;||
|The X-rectangles should be replaced with images only if an image was submitted for the cluck. This would be the same image_url saved from the form above.|&#10003;||
|Image should be used in place of the rooster avatar|&#10003;||
|both "/" and "/clucks" should send user to this inde page|&#10003;|one of the routes should be redirecting to the other instead of both rendering|

------

# Part 6: Navigation Bar
### Value: 15%
## Score: 15/15%

|Feature |Mark |Notes |
|--------|-----|------|
|There should be a "chicken" icon for the brand.|&#10003;||
|Clicking the brand sends the user to the index.|&#10003;||
|The "Cluck!" button should link to the new cluck form.|&#10003;||
|It should have a "Sign In" button that links to the /sign_in page.|&#10003;||
|When the user is signed in, display their name instead of the "Sign In" button.|&#10003;||

------
# Part 7: Styling
### Value: 10%
## Score: 8/10%

|Feature |Mark |Notes |
|--------|-----|------|
|Attempt to style the pages you've created previously to look like their wireframes using a CSS stylesheet you are loading with a static assets directory.|&#10003;||

------

##### Bonus: Human Friendly Creation Date
##### Value: 5%
 
> Display the created_at date for clucks in a human friendly readable way.

> Display the created_at date besides the username as show in any wireframe with clucks.
> Use plain language to show the date relative to the current date. (e.g. yesterday would appear as 1 day ago, 22 minutes ago, 2 hours ago, etc)
> Anything less than a minute ago should show as Just now

------

##### Bonus: Trending Tags
##### Value: 5%

> Add a trending tags section that only appears in sizes larger than mobile as shown below.

> If the user enters a hashtag (such as #Things), then store them in another table alongside a counter with the number of time the hashtag was used.
> Whenever a cluck is created that contains hashtags that already exists, increment each of their counter fields.
> Use that data to make the "Trending Clucks" section functional.
> Sort them by their counter field in a descending order.

**Comment by ansonws** [comment]
Hey Brandon, I also created a Node module to display human readable dates on the Clucks. I was wondering if I required it correctly and if it's displaying correctly on your machine? Thanks

**Comment by QuickStyles** [comment]
I don't think it worked on my machine... What file is the code in?

**Comment by ansonws** [comment]
The module is in "custom_modules/creationDate.js" and it was required in "routes/clucks.js"

**Pull request merged**
